routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $site_title = "Minu leht"; //backend poolt saadetud andmed
    $name = request('name'); //GET parameetriga saadetud andmed
    return view('welcome', ['site_title' => $site_title, 'name' => $name]);
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/article', 'articleController');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //table name has to be specified ONLY if table name is not model name in plurar(mitmuses)
    //protected $table = 'articles';
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Article;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        //return view('home');
        $ownedArticles = Article::where('author_id', Auth::id())->get();
        //return view('home',$ownedArticles);
        //varem sai ka nii:
        return view ('home')->with('articles',$ownedArticles);

    }
}

//controllereid uurida!!!

app/Http/Controllers/articleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Article;

class articleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   //get articles from database
        $articles = Article::all();
        $total = Article::all()->count();

        //pass articles to"articles all" view
        return view ('articles.all',['total' => $total, 'articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //siin kuvab resourcest articles create.blade
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this -> validate($request,[
            'title' => 'required|string|max:225|min:1',
            'description' => 'required|string|max:225|min:1',
            'content' => 'required|string|max:10000|min:1'

        ]);
        //create new instance of article from form data
        $article = new Article();
        //save data to new instance

        $article->title = $request->title;

        $article->description = $request->description;

        $article->content = $request->content;

        $article->author_id = Auth::id();
        //store data as a new row in database
        $article->save();
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //get the specified article from database
        $article = Article::find($id);
        //display the current article
       
        
        return view('articles.single')->with('article',$article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //TODO: check if user has rights to edit this article
        //get the article from the database
        $article = Article::find($id);
        //show form for editing and fill it with data from database
        return view('articles.edit')->with('article', $article);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      //
      $article = Article::find($id);
      $article->title = $request->title;
      $article->description = $request->description;
      $article->content = $request->content;
      $article->save();
      return redirect()->route('article.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $article = Article::find($id);
        //TODO: check if the article belong to the currently logged in user
        if($article->author_id == Auth::id()){ //kui inimene pole sisse logitud, siis == 0
            $article->delete();
            //ümbersuunamine nüüd:
            return redirect()->route('home');
        }else{
            return view('404')->with(['status' => '401', 'error' => 'Bad credentials' ]);//see tekitab errori

        }
    }
}

app/Http/Controllers/fileUploadController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class fileUploadController extends Controller
{
    //
}

resources/views/articles/all.blade.php
@extends('layouts.app')

@section('content')
<div>
    <h1> Articles({{ $total }}) </h1>
        @foreach ($articles as $article)
        <h2><a href="{{route ('article.show', $article->id)}}" >{{$article->title}}</a></h2>
        <p>{{$article->description}}</p>
    @endforeach
</div>

@endsection

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <form action="{{route ('article.store')}}" method="POST">
        @csrf <!--Uurida mis see teeb-->
        <div class="form-group">
            <label for="title">Article title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="form-group">
            <label for="description">Article short description</label>
            <textarea class="form-control" id="description" name="description" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="content">Article body</label>
            <textarea class="form-control" id="content" name="content" rows="15"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{route('article.update', $article->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="title">Article title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $article->title }}">
        </div>
        <div class="form-group">
            <label for="description">Article short description</label>
            <textarea class="form-control" id="description" name="description" rows="3">{{ $article->description }}</textarea>
        </div>
        <div class="form-group">
            <label for="content">Article body</label>
            <textarea class="form-control" id="content" name="content" rows="15">{{ $article->content }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
@endsection

resources/views/articles/single.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h1> {{ $article->title }} </h1>
    <p class="text-muted"> {{ $article->description}}</p>
    <p>{{ $article->content }}</p>
    <a class="btn btn-secondary" href="{{ route('home') }}">Back</a>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <ul class="list-group list-group-flush">
                        @foreach ($articles as $article)
                            <li class="list-group-item">
                                <div class="d-flex">
                                    <div class="p-2 flex-grow-1">
                                        <a href="{{ route('article.show', $article->id) }}">{{ $article->title }}</a>
                                    </div>
                                    <div class="p-2 d-flex flex-row-reverse text-">
                                        <a class="btn btn-primary" href="{{ route('article.edit',$article->id) }}">EDIT</a>
                                        <form action="{{ route('article.destroy',$article->id)}}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">DEL</a>
                                        </form> 
                                    </div>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                    <a class="btn btn-success" href="{{ route('article.create')}}">Add new article</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/404.blade.php
@extends('layouts.app')

@section('content')


<div class="container d-flex justify-content-center aligne-items-center">
    <h1>
        <strong>
            {{$status ?? '404'}} 
        </strong>
        {{$error}}
    </h1>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>